/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/workspaces": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a new workspace */
		post: operations["createWorkspace"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		Workspace: {
			/** Format: uuid */
			id: string;
			name: string;
			/** @description baseline rate */
			default_hourly_rate: number;
			description?: string | null;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		CreateWorkspaceRequest: {
			name: string;
			default_hourly_rate: number;
			description?: string | null;
		};
		/**
		 * @description RFC 7807 Problem Details. The error shape for every non-2xx response
		 *     in the API. `type` names the error class; `errors` (validation only)
		 *     maps field names to human-readable messages.
		 */
		ProblemDetail: {
			/**
			 * Format: uri
			 * @description A URI reference that identifies the problem type.
			 * @default about:blank
			 */
			type: string;
			/** @description A short, human-readable summary of the problem type. */
			title: string;
			/** @description The HTTP status code generated by the origin server for this occurrence of the problem. */
			status: number;
			/** @description A human-readable explanation specific to this occurrence of the problem. */
			detail?: string;
			/**
			 * Format: uri
			 * @description A URI reference that identifies the specific occurrence of the problem.
			 */
			instance?: string;
		} & {
			[key: string]: unknown;
		};
	};
	responses: {
		/**
		 * @description Malformed request or validation failure. Malformed JSON, unknown
		 *     fields, invalid enum values, bad UUIDs, and rule violations (e.g. an
		 *     empty PATCH) all land here. Field-level detail in `Problem.errors`.
		 */
		BadRequest: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/problem+json": components["schemas"]["ProblemDetail"];
			};
		};
		/**
		 * @description Unexpected server failure. The response deliberately carries no
		 *     internal detail; correlate via the request id in server logs.
		 */
		InternalError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/problem+json": components["schemas"]["ProblemDetail"];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	createWorkspace: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateWorkspaceRequest"];
			};
		};
		responses: {
			/**
			 * @description Created. The response is the complete workspace. Including the
			 *     server-assiged identifier, and expanded summaries.
			 */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Workspace"];
				};
			};
			400: components["responses"]["BadRequest"];
			500: components["responses"]["InternalError"];
		};
	};
}
