// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Priority string

const (
	PriorityCritical Priority = "critical"
	PriorityHigh     Priority = "high"
	PriorityMedium   Priority = "medium"
	PriorityLow      Priority = "low"
)

func (e *Priority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priority(s)
	case string:
		*e = Priority(s)
	default:
		return fmt.Errorf("unsupported scan type for Priority: %T", src)
	}
	return nil
}

type NullPriority struct {
	Priority Priority `json:"priority"`
	Valid    bool     `json:"valid"` // Valid is true if Priority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriority) Scan(value interface{}) error {
	if value == nil {
		ns.Priority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priority), nil
}

type TicketStatus string

const (
	TicketStatusBacklog    TicketStatus = "backlog"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusInReview   TicketStatus = "in_review"
	TicketStatusDone       TicketStatus = "done"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type TimeEntryStatus string

const (
	TimeEntryStatusPending TimeEntryStatus = "pending"
	TimeEntryStatusCleared TimeEntryStatus = "cleared"
)

func (e *TimeEntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeEntryStatus(s)
	case string:
		*e = TimeEntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeEntryStatus: %T", src)
	}
	return nil
}

type NullTimeEntryStatus struct {
	TimeEntryStatus TimeEntryStatus `json:"time_entry_status"`
	Valid           bool            `json:"valid"` // Valid is true if TimeEntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TimeEntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeEntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeEntryStatus), nil
}

type Project struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	HourlyRateOverride *int32             `json:"hourly_rate_override"`
	Archived           bool               `json:"archived"`
	TicketCounter      int32              `json:"ticket_counter"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Settlement struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	TotalAmount int32              `json:"total_amount"`
	ClearedAt   pgtype.Timestamptz `json:"cleared_at"`
}

type Ticket struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Identifier  string             `json:"identifier"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      TicketStatus       `json:"status"`
	Priority    Priority           `json:"priority"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TimeEntry struct {
	ID              pgtype.UUID        `json:"id"`
	TicketID        pgtype.UUID        `json:"ticket_id"`
	SettlementID    pgtype.UUID        `json:"settlement_id"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsBillable      bool               `json:"is_billable"`
	Status          TimeEntryStatus    `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	DefaultHourlyRate int32              `json:"default_hourly_rate"`
	Description       string             `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
