// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Priority string

const (
	PriorityCritical Priority = "critical"
	PriorityHigh     Priority = "high"
	PriorityMedium   Priority = "medium"
	PriorityLow      Priority = "low"
)

func (e *Priority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Priority(s)
	case string:
		*e = Priority(s)
	default:
		return fmt.Errorf("unsupported scan type for Priority: %T", src)
	}
	return nil
}

type NullPriority struct {
	Priority Priority `json:"priority"`
	Valid    bool     `json:"valid"` // Valid is true if Priority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriority) Scan(value interface{}) error {
	if value == nil {
		ns.Priority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Priority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Priority), nil
}

type TicketStatus string

const (
	TicketStatusBacklog    TicketStatus = "backlog"
	TicketStatusInProgress TicketStatus = "in_progress"
	TicketStatusInReview   TicketStatus = "in_review"
	TicketStatusDone       TicketStatus = "done"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type TimeEntryStatus string

const (
	TimeEntryStatusPending TimeEntryStatus = "pending"
	TimeEntryStatusCleared TimeEntryStatus = "cleared"
)

func (e *TimeEntryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TimeEntryStatus(s)
	case string:
		*e = TimeEntryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TimeEntryStatus: %T", src)
	}
	return nil
}

type NullTimeEntryStatus struct {
	TimeEntryStatus TimeEntryStatus `json:"time_entry_status"`
	Valid           bool            `json:"valid"` // Valid is true if TimeEntryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTimeEntryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TimeEntryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TimeEntryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTimeEntryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TimeEntryStatus), nil
}

type Account struct {
	ID                    string             `json:"id"`
	AccountId             string             `json:"accountId"`
	ProviderId            string             `json:"providerId"`
	UserId                string             `json:"userId"`
	AccessToken           *string            `json:"accessToken"`
	RefreshToken          *string            `json:"refreshToken"`
	IdToken               *string            `json:"idToken"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refreshTokenExpiresAt"`
	Scope                 *string            `json:"scope"`
	Password              *string            `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type Jwk struct {
	ID         string             `json:"id"`
	PublicKey  string             `json:"publicKey"`
	PrivateKey string             `json:"privateKey"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	Alg        *string            `json:"alg"`
	Crv        *string            `json:"crv"`
}

type Project struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	HourlyRateOverride *int32             `json:"hourly_rate_override"`
	Archived           bool               `json:"archived"`
	TicketCounter      int32              `json:"ticket_counter"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string             `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
	IpAddress *string            `json:"ipAddress"`
	UserAgent *string            `json:"userAgent"`
	UserId    string             `json:"userId"`
}

type Settlement struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	TotalAmount int32              `json:"total_amount"`
	ClearedAt   pgtype.Timestamptz `json:"cleared_at"`
}

type Ticket struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Identifier  string             `json:"identifier"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      TicketStatus       `json:"status"`
	Priority    Priority           `json:"priority"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TimeEntry struct {
	ID              uuid.UUID          `json:"id"`
	TicketID        uuid.UUID          `json:"ticket_id"`
	SettlementID    pgtype.UUID        `json:"settlement_id"`
	DurationMinutes int32              `json:"duration_minutes"`
	IsBillable      bool               `json:"is_billable"`
	Status          TimeEntryStatus    `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	EmailVerified   bool               `json:"emailVerified"`
	Image           *string            `json:"image"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	Username        *string            `json:"username"`
	DisplayUsername *string            `json:"displayUsername"`
}

type Verification struct {
	ID         string             `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type Workspace struct {
	ID                uuid.UUID          `json:"id"`
	OwnerID           string             `json:"owner_id"`
	Name              string             `json:"name"`
	DefaultHourlyRate int32              `json:"default_hourly_rate"`
	Description       *string            `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
