// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, name, hourly_rate_override)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, description, hourly_rate_override, archived, ticket_counter, created_at, updated_at
`

type CreateProjectParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	Name               string      `json:"name"`
	HourlyRateOverride *int32      `json:"hourly_rate_override"`
}

// PROJECTS --
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.WorkspaceID, arg.Name, arg.HourlyRateOverride)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.HourlyRateOverride,
		&i.Archived,
		&i.TicketCounter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT id, workspace_id, name, description, hourly_rate_override, archived, ticket_counter, created_at, updated_at FROM projects
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.HourlyRateOverride,
			&i.Archived,
			&i.TicketCounter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectCounter = `-- name: UpdateProjectCounter :one
UPDATE projects
SET ticket_counter = ticket_counter + 1, updated_at = NOW()
WHERE id = $1
RETURNING ticket_counter
`

func (q *Queries) UpdateProjectCounter(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, updateProjectCounter, id)
	var ticket_counter int32
	err := row.Scan(&ticket_counter)
	return ticket_counter, err
}
