// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (workspace_id, total_amount)
VALUES ($1, $2)
RETURNING id, workspace_id, total_amount, cleared_at
`

type CreateSettlementParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	TotalAmount int32     `json:"total_amount"`
}

// SETTLEMENTS --
func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement, arg.WorkspaceID, arg.TotalAmount)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TotalAmount,
		&i.ClearedAt,
	)
	return i, err
}
