// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    project_id, identifier, title, description, status, priority, created_by
) VALUES (
$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, identifier, title, description, status, priority, created_by, assignee, due_date, created_at, updated_at
`

type CreateTicketParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Identifier  string      `json:"identifier"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Status      Status      `json:"status"`
	Priority    Priority    `json:"priority"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Identifier,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.CreatedBy,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedBy,
		&i.Assignee,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
SELECT id, project_id, identifier, title, description, status, priority, created_by, assignee, due_date, created_at, updated_at FROM tickets
WHERE project_id = $1
AND identifier = $2
`

type DeleteParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	Identifier string      `json:"identifier"`
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) error {
	_, err := q.db.Exec(ctx, delete, arg.ProjectID, arg.Identifier)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT id, project_id, identifier, title, description, status, priority, created_by, assignee, due_date, created_at, updated_at FROM tickets
WHERE project_id = $1
AND identifier = $2
`

type GetTicketParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	Identifier string      `json:"identifier"`
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.ProjectID, arg.Identifier)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedBy,
		&i.Assignee,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
