// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    project_id, identifier, title, description, status, priority, tags
) VALUES (
$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, identifier, title, description, status, priority, tags, created_at, updated_at
`

type CreateTicketParams struct {
	ProjectID   uuid.UUID    `json:"project_id"`
	Identifier  string       `json:"identifier"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      TicketStatus `json:"status"`
	Priority    Priority     `json:"priority"`
	Tags        []string     `json:"tags"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Identifier,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Tags,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, project_id, identifier, title, description, status, priority, tags, created_at, updated_at FROM tickets
WHERE project_id = $1
AND identifier = $2
`

type GetTicketParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	Identifier string    `json:"identifier"`
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.ProjectID, arg.Identifier)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByProject = `-- name: ListTicketsByProject :many
SELECT id, project_id, identifier, title, description, status, priority, tags, created_at, updated_at FROM tickets
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTicketsByProject(ctx context.Context, projectID uuid.UUID) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Identifier,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
