// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_entries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearPendingTimeEntries = `-- name: ClearPendingTimeEntries :exec
UPDATE time_entries
SET status = 'CLEARED', settlement_id = $2, updated_at = NOW()
WHERE id = ANY($1::UUID[])
`

type ClearPendingTimeEntriesParams struct {
	Column1      []uuid.UUID `json:"column_1"`
	SettlementID pgtype.UUID `json:"settlement_id"`
}

func (q *Queries) ClearPendingTimeEntries(ctx context.Context, arg ClearPendingTimeEntriesParams) error {
	_, err := q.db.Exec(ctx, clearPendingTimeEntries, arg.Column1, arg.SettlementID)
	return err
}

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entries (ticket_id, duration_minutes, is_billable, status)
VALUES ($1, $2, $3, 'PENDING')
RETURNING id, ticket_id, settlement_id, duration_minutes, is_billable, status, created_at, updated_at
`

type CreateTimeEntryParams struct {
	TicketID        uuid.UUID `json:"ticket_id"`
	DurationMinutes int32     `json:"duration_minutes"`
	IsBillable      bool      `json:"is_billable"`
}

// TIME-ENTRIES --
func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, createTimeEntry, arg.TicketID, arg.DurationMinutes, arg.IsBillable)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SettlementID,
		&i.DurationMinutes,
		&i.IsBillable,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTimeEntriesByWorkspace = `-- name: ListPendingTimeEntriesByWorkspace :many
SELECT te.id, te.ticket_id, te.settlement_id, te.duration_minutes, te.is_billable, te.status, te.created_at, te.updated_at FROM time_entries te
JOIN tickets t ON te.ticket_id = t.id
JOIN projects p ON t.project_id = p.id
WHERE p.workspace_id = $1 AND te.status = 'PENDING'
`

func (q *Queries) ListPendingTimeEntriesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, listPendingTimeEntriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.SettlementID,
			&i.DurationMinutes,
			&i.IsBillable,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
