// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (owner_id, name, default_hourly_rate, description)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, default_hourly_rate, description, created_at, updated_at
`

type CreateWorkspaceParams struct {
	OwnerID           string  `json:"owner_id"`
	Name              string  `json:"name"`
	DefaultHourlyRate int32   `json:"default_hourly_rate"`
	Description       *string `json:"description"`
}

// WORKSPACES --
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.OwnerID,
		arg.Name,
		arg.DefaultHourlyRate,
		arg.Description,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.DefaultHourlyRate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces
WHERE id = $1 AND owner_id = $2
`

type DeleteWorkspaceParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, owner_id, name, default_hourly_rate, description, created_at, updated_at FROM workspaces
WHERE id = $1 AND owner_id = $2
`

type GetWorkspaceByIDParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID string    `json:"owner_id"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, arg GetWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, arg.ID, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.DefaultHourlyRate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, owner_id, name, default_hourly_rate, description, created_at, updated_at FROM workspaces
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context, ownerID string) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.DefaultHourlyRate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
