// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, default_hourly_rate)
VALUES ($1, $2)
RETURNING id, name, default_hourly_rate, description, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Name              string `json:"name"`
	DefaultHourlyRate int32  `json:"default_hourly_rate"`
}

// WORKSPACES --
func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Name, arg.DefaultHourlyRate)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultHourlyRate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, default_hourly_rate, description, created_at, updated_at FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultHourlyRate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, default_hourly_rate, description, created_at, updated_at FROM workspaces
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultHourlyRate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
