// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    project_id, identifier, title, description, status, priority, created_by, assignee, due_date
) VALUES (
$1, $2, $3, $4, $5, $6 , $7, $8, $9
)
RETURNING id, project_id, identifier, title, description, status, priority, created_by, assignee, due_date, created_at, updated_at
`

type CreateTicketParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	Identifier  string             `json:"identifier"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      Status             `json:"status"`
	Priority    Priority           `json:"priority"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	Assignee    pgtype.UUID        `json:"assignee"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Identifier,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.CreatedBy,
		arg.Assignee,
		arg.DueDate,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedBy,
		&i.Assignee,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, project_id, identifier, title, description, status, priority, created_by, assignee, due_date, created_at, updated_at FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Identifier,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedBy,
		&i.Assignee,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
